[package]
name = "mem-heartbeat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
page_size = "0.6"
lazy_static = "1.4"
libc = "0.2"
# Before upgrade to ByteSize
systemstat = "=0.1.0"
